export const architectureSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  title: "ArchitectViz Architecture",
  type: "object",
  required: ["architecture", "lastUpdated", "description", "components", "connections"],
  additionalProperties: true,
  properties: {
    architecture: { type: "string", description: "Nom de l'architecture cartographiée" },
    type: {
      type: "string",
      enum: ["FULLSTACK", "BACKEND", "FRONTEND", "MICROSERVICES", "MONOLITH", "DATA", "OTHER"],
    },
    version: {
      type: "string",
      pattern: "^\\d+\\.\\d+\\.\\d+",
      description: "SemVer du document — ex. 1.0.0",
    },
    lastUpdated: {
      type: "string",
      description: "Date ISO YYYY-MM-DD",
    },
    description: { type: "string" },
    layers: {
      type: "array",
      items: {
        type: "object",
        required: ["name", "color", "description"],
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          color: {
            type: "string",
            pattern: "^#[0-9A-Fa-f]{6}$",
            description: "Hex couleur (#RRGGBB)",
          },
          description: { type: "string" },
        },
      },
    },
    components: {
      type: "array",
      items: { $ref: "#/definitions/component" },
    },
    connections: {
      type: "array",
      items: { $ref: "#/definitions/connection" },
    },
    flow_summary: {
      type: "object",
      additionalProperties: true,
      properties: {
        user_flow: { type: "string" },
        technologies_count: { type: "number" },
        backend_endpoints: { type: "number" },
        frontend_routes: { type: "number" },
        external_services: { type: "number" },
      },
    },
    warnings: {
      type: "array",
      items: {
        type: "object",
        required: ["severity", "message", "component"],
        additionalProperties: true,
        properties: {
          severity: { type: "string", enum: ["WARNING", "INFO", "CRITICAL"] },
          message: { type: "string" },
          component: { type: "string" },
          suggestion: { type: "string" },
        },
      },
    },
    validation_checklist: {
      type: "object",
      additionalProperties: { type: "string" },
    },
    next_steps: {
      type: "array",
      items: { type: "string" },
    },
  },
  definitions: {
    payloadField: {
      type: "array",
      description: "Champs du payload (contrat d'API) — dérivés du DTO/modèle",
      items: {
        type: "object",
        required: ["name"],
        additionalProperties: true,
        properties: {
          name: { type: "string" },
          type: { type: "string" },
          description: { type: "string" },
          required: { type: "boolean" },
        },
      },
    },
    component: {
      type: "object",
      required: ["id", "label", "type", "layer", "technology"],
      additionalProperties: true,
      properties: {
        id: {
          type: "string",
          pattern: "^[a-z0-9_-]+$",
          description: "Identifiant unique — minuscules, chiffres, _ ou -",
        },
        label: { type: "string" },
        type: {
          type: "string",
          enum: [
            "frontend",
            "backend",
            "cache",
            "db",
            "queue",
            "mq",
            "batch",
            "etl",
            "iam",
            "monitoring",
            "service",
            "third-party",
          ],
          description:
            "frontend, backend, cache (in-memory), db (persistance), queue (file de tâches), mq (message broker), batch (job planifié), etl (pipeline data), iam (auth/autorisation), monitoring (observabilité), service (service interne générique), third-party (externe)",
        },
        layer: { type: "string", description: "Doit correspondre à layers[].name" },
        technology: { type: "string" },
        url: { type: "string" },
        port: { type: "number", minimum: 0, maximum: 65535 },
        description: { type: "string" },
        state_management: { type: "string" },
        build_tool: { type: "string" },
        deployment: { $ref: "#/definitions/deployment" },
        routes: {
          type: "array",
          items: { $ref: "#/definitions/route" },
        },
        endpoints: {
          type: "array",
          items: { $ref: "#/definitions/endpoint" },
        },
        authentication: { $ref: "#/definitions/authentication" },
        consumed_via: { type: "string" },
        note: { type: "string" },
        external_ref: {
          type: "string",
          description:
            "Lien explicite vers une autre architecture cartographiée (slug de fichier ou nom d'architecture). Prioritaire sur la détection heuristique.",
        },
        cached_data: {
          type: "array",
          items: {
            type: "object",
            required: ["key_pattern", "ttl", "purpose"],
            additionalProperties: true,
            properties: {
              endpoint: { type: "string" },
              key_pattern: { type: "string" },
              ttl: { type: "string" },
              purpose: { type: "string" },
            },
          },
        },
        http_client_config: { type: "object", additionalProperties: { type: "string" } },
        key_dependencies: { type: "array", items: { type: "string" } },
        used_by: { type: "array", items: { type: "string" } },
        owner: { type: "string", description: "Personne ou rôle responsable" },
        team: { type: "string", description: "Équipe propriétaire" },
        criticality: {
          type: "string",
          enum: ["low", "medium", "high", "critical"],
          description: "Criticité métier du composant",
        },
        environment: { type: "string", description: "Environnement (prod, staging, dev…)" },
        provenance: {
          type: "string",
          enum: ["auto", "llm", "manual"],
          description: "Origine de la donnée : extracteur déterministe, LLM, ou humain",
        },
        confidence: { type: "number", minimum: 0, maximum: 1 },
      },
    },
    connection: {
      type: "object",
      required: ["id", "from", "to", "protocol", "description"],
      additionalProperties: true,
      properties: {
        id: { type: "string", pattern: "^[a-z0-9_-]+$" },
        from: { type: "string", description: "ID du composant source" },
        to: { type: "string", description: "ID du composant cible" },
        protocol: { type: "string", description: "Ex. REST/HTTPS, gRPC, Kafka, JDBC, Redis" },
        authenticated: { type: "boolean" },
        description: { type: "string" },
        latency: { type: "string" },
        note: { type: "string" },
        client: { type: "string" },
        flow: { type: "string" },
        cache_strategy: { type: "string" },
        ttl: { type: "string" },
        operations: { type: "array", items: { type: "string" } },
        endpoints: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: true,
            properties: {
              frontend_call: { type: "string" },
              backend_endpoint: { type: "string" },
              path: { type: "string" },
              method: { type: "string" },
              pages: { type: "array", items: { type: "string" } },
              query_params: { type: "array", items: { type: "string" } },
              description: { type: "string" },
              authenticated: { type: "boolean" },
            },
          },
        },
        endpoint_mappings: {
          type: "array",
          items: {
            type: "object",
            required: ["frontend_endpoint", "backend_endpoint", "method", "purpose"],
            additionalProperties: true,
            properties: {
              frontend_endpoint: { type: "string" },
              backend_endpoint: { type: "string" },
              method: { type: "string" },
              frontend_pages: { type: "array", items: { type: "string" } },
              purpose: { type: "string" },
              query_params: { type: "string" },
              path_params: { type: "string" },
              request_body: { type: "string" },
              status: { type: "string" },
              authenticated: { type: "boolean" },
            },
          },
        },
      },
    },
    deployment: {
      type: "object",
      required: ["platform"],
      additionalProperties: true,
      properties: {
        platform: { type: "string" },
        region: { type: "string" },
        ci_cd: { type: "string" },
        module_federation: { type: ["string", "boolean"] },
        containerized: { type: "boolean" },
        orchestration: { type: "string" },
        scaling: { type: "string" },
        note: { type: "string" },
      },
    },
    route: {
      type: "object",
      required: ["path", "label", "authenticated", "description"],
      additionalProperties: true,
      properties: {
        path: { type: "string" },
        label: { type: "string" },
        authenticated: { type: "boolean" },
        description: { type: "string" },
        api_calls: { type: "array", items: { type: "string" } },
      },
    },
    endpoint: {
      type: "object",
      required: ["path", "method"],
      additionalProperties: true,
      properties: {
        path: { type: "string" },
        method: {
          type: "string",
          enum: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
        },
        description: { type: "string" },
        authenticated: { type: "boolean" },
        params: { type: "object", additionalProperties: true },
        response_schema: { type: "string" },
        status_codes: { type: "array", items: { type: "number" } },
        note: { type: "string" },
        mapped_from_frontend: { type: "string" },
        validation: {
          type: "string",
          description: "Statut de validation. Valeurs canoniques : VALID | UNVERIFIED | INVALID (les anciens libellés emoji restent acceptés).",
        },
        provenance: { type: "string", enum: ["auto", "llm", "manual"] },
        confidence: { type: "number", minimum: 0, maximum: 1 },
        response_fields: { $ref: "#/definitions/payloadField" },
        request_fields: { $ref: "#/definitions/payloadField" },
      },
    },
    authentication: {
      type: "object",
      required: ["type", "provider"],
      additionalProperties: true,
      properties: {
        type: { type: "string" },
        provider: { type: "string" },
        token_expiry: { type: "string" },
        roles_permissions: { type: "string" },
        token_format: { type: "string" },
        note: { type: "string" },
      },
    },
  },
} as const;
